# Generated by Django 3.0.5 on 2020-05-01 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20200430_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_applicant_user',
        ),
    ]
