# Generated by Django 3.0.5 on 2020-04-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_applicant_user',
            field=models.BooleanField(default=False, verbose_name='Es usuario aspirante'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_business_user',
            field=models.BooleanField(default=False, verbose_name='Es usuario empresarial'),
        ),
    ]
