# Generated by Django 3.0.5 on 2020-04-30 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20200429_1345'),
        ('usuario', '0002_auto_20200428_2241'),
    ]

    operations = [
    ]
