# Generated by Django 3.0.5 on 2020-05-01 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20200430_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_applicant_user',
            new_name='is_candidate_user',
        ),
    ]
