# Generated by Django 3.0.5 on 2020-05-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_remove_usuario_is_applicant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=30, verbose_name='Nombre de usuario'),
        ),
    ]
