# Generated by Django 3.0.5 on 2020-05-01 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20200430_2308'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
