# Generated by Django 3.0.5 on 2020-04-29 18:45

import convocatoria.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=60, verbose_name='Cargo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('closing_date_time', models.DateTimeField(verbose_name='Fecha y hora de cierre')),
                ('status', models.CharField(choices=[('1', 'Abierta'), ('2', 'Cerrada'), ('3', 'Terminada')], default='1', max_length=2, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha y hora de última actualización')),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
            },
        ),
        migrations.CreateModel(
            name='PostulacionAnonima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80, verbose_name='Nombre completo')),
                ('curriculum', convocatoria.validators.ContentTypeRestrictedFileField(upload_to='curriculums/', verbose_name='Curriculo')),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de postulación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha y hora de última actualización')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convocatoria.Convocatoria', verbose_name='convocatoria')),
            ],
        ),
    ]
