# Generated by Django 3.0.5 on 2020-05-01 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0004_auto_20200430_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convocatoria',
            name='candidate_applications',
        ),
        migrations.AddField(
            model_name='postulacion',
            name='announcement',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='convocatoria.Convocatoria', verbose_name='aspirante'),
            preserve_default=False,
        ),
    ]
