# Generated by Django 3.0.5 on 2020-04-30 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0002_auto_20200430_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulacion',
            old_name='aspirate',
            new_name='candidate',
        ),
    ]
